version: 2
# Gradle and GitHub Actions updates are combined into a single pull request
# https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/configuring-multi-ecosystem-updates
multi-ecosystem-groups:
  versions:
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 1
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: "versions"
    rebase-strategy: "disabled"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: "versions"
    rebase-strategy: "disabled"
