version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Moscow"
    rebase-strategy: "auto"
    open-pull-requests-limit: 1
    groups:
      versions:
        dependency-type: production
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Moscow"
    rebase-strategy: "auto"
    open-pull-requests-limit: 1
    groups:
      versions:
        dependency-type: production
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch
