//import org.jetbrains.kotlin.js.dce.InputResource.Companion.file
//import org.jetbrains.kotlin.konan.properties.saveToFile
import java.util.Properties
import java.io.FileInputStream

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    `java-library`
    kotlin("jvm") version "1.5.21"
    id("com.github.johnrengelman.shadow") version "7.1.0"
}


var gprUser: String? = null
var gprPassword: String? = null
var versionBuildRelease = 0
task("Get GPR user password") {
    val astraPropsFile = file("astra.properties")
    if (!astraPropsFile.exists())
        astraPropsFile.createNewFile()
    val astraProps = Properties().apply { load(FileInputStream(astraPropsFile)) }
    gprUser = astraProps.getProperty("gpr.user")
    gprPassword = astraProps.getProperty("gpr.password")
    if (gprUser == null || gprPassword == null) {
        if (gprUser == null)
            astraProps.setProperty("gpr.user", "SET_GPR_USERNAME_HERE")
        if (gprPassword == null)
            astraProps.setProperty("gpr.password", "SET_GPR_KEY_HERE")
        astraProps.store(astraPropsFile.outputStream(), "")
        throw GradleException("You need to set your GPR keys")
    }
}
task("Get versionBuildRelease"){
    val versionPropsFile = file("version.properties")
    if (!versionPropsFile.exists())
        versionPropsFile.createNewFile()
    val versionProps = Properties().apply { load(FileInputStream(versionPropsFile)) }
    versionBuildRelease = (versionProps.getProperty("VERSION_BUILD_RELEASE","0").toIntOrNull())?:0
    versionProps.setProperty("VERSION_BUILD_RELEASE","${++versionBuildRelease}")
    versionProps.store(versionPropsFile.outputStream(),"")
}
group = "com.astrainteractive"
version = "2.1.$versionBuildRelease"
val name = "AstraTemplate"
description = "Template plugin from AstraInteractive"
java.sourceCompatibility = JavaVersion.VERSION_17
repositories {
    mavenLocal()
    mavenCentral()
    maven("https://repo.maven.apache.org/maven2/")
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/Astra-Interactive/AstraLibs")
        credentials {
            username = gprUser
            password = gprPassword
        }
        metadataSources {
            artifact()
        }
    }
    maven("https://repo1.maven.org/maven2/")
    maven("https://papermc.io/repo/repository/maven-public/")
    maven("https://repo.dmulloy2.net/repository/public/")
    maven("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    maven("https://maven.enginehub.org/repo/")
}

dependencies {
    implementation("com.astrainteractive:astralibs:1.1.9-8")
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.21")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.0")
    compileOnly("io.papermc.paper:paper-api:1.18.1-R0.1-SNAPSHOT")
    compileOnly("com.comphenix.protocol:ProtocolLib:4.7.0")
    compileOnly("me.clip:placeholderapi:2.10.9")
    testImplementation("junit:junit:4.13.1")
    testImplementation("com.github.seeseemelk:MockBukkit-v1.18:1.24.1")
    testImplementation("io.kotest:kotest-runner-junit5:latest.release")
    testImplementation("io.kotest:kotest-assertions-core:latest.release")
    testImplementation(kotlin("test"))
}



publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
tasks.withType<Test> {
    useJUnitPlatform()
}
tasks {
    processResources {
        from(sourceSets.main.get().resources.srcDirs) {
            filesMatching("plugin.yml") {
                expand(
                    "name" to project.name,
                    "version" to project.version,
                    "description" to project.description
                )
            }
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }
    }

    compileJava {
        options.encoding = "UTF-8"
    }
}