services:
  # For command call use `docker exec mc_docker_astratemplate rcon-cli <your_command>`
  mc_docker_astratemplate:
    restart: no
    container_name: mc_docker_astratemplate
    image: itzg/minecraft-server # https://github.com/itzg/docker-minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      LEVEL_TYPE: FLAT
      EXISTING_OPS_FILE: MERGE
      OPS: |
        RomaRoman
      EULA: true
      ONLINE_MODE: false
      # NeoForge --------------------
      #      TYPE: NEOFORGE
      #      VERSION: "1.20.1"
      #      NEOFORGE_VERSION: "21.1.129"
      # Forge --------------------
      TYPE: FORGE
      VERSION: "1.20.1"
      FORGE_VERSION: "47.4.12"
      # Paper --------------------
      #      TYPE: PAPER
      #      VERSION: 1.21.8
      # Custom -------------------
    #      CUSTOM_SERVER: https://api.papermc.io/v2/projects/paper/versions/1.21.1/builds/121/downloads/paper-1.21.1-121.jar
    volumes:
      - ./build/forge:/data # Forge
#            - ./build/neoforge:/data # NeoForge
#      - ./build/bukkit:/data # Bukkit/Paper/Spigot
#      - ./build/velocity:/data # Velocity
#      - ./build/fabric:/data # Fabric