# Gradle
kotlin.code.style=official
kotlin.incremental=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.isolated-projects=false
# Java
klibs.java.source=8
klibs.java.target=25
klibs.java.ktarget=25
# Project
klibs.project.name=AstraTemplate
klibs.project.group=ru.astrainteractive.astratemplate
klibs.project.version.string=9.3.0
klibs.project.description=Template plugin for EmpireProjekt
klibs.project.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com
klibs.project.url=https://github.com/Astra-Interactive/AstraTemplate
klibs.publish.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com
