name: "Upload GitHub release"
on:
  workflow_call:
    secrets:
      ACTIONS_TOKEN:
        required: true
jobs:
  upload_github_release:
    name: Upload GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v6

      - uses: christian-draeger/read-properties@1.1.1
        id: properties
        with:
          path: './gradle.properties'
          properties: 'klibs.project.name klibs.project.version.string'

      - uses: actions/download-artifact@d0ce8fd1167ed839810201de977912a090ab10a7
        name: "Download bukkit"
        with:
          name: bukkit
          path: ./jars
      - uses: actions/download-artifact@d0ce8fd1167ed839810201de977912a090ab10a7
        name: "Download forge"
        with:
          name: bungee
          path: ./jars
      - uses: actions/download-artifact@d0ce8fd1167ed839810201de977912a090ab10a7
        name: "Download neoforge"
        with:
          name: bungee
          path: ./jars

      - name: Create release
        id: create_internal_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          files: |
            ./jars/*.jar
          tag_name: ${{ steps.properties.outputs.klibs-project-version-string }}
          name: ${{ steps.properties.outputs.klibs-project-name }} - ${{ steps.properties.outputs.klibs-project-version-string }}
          draft: false
          prerelease: false
