name: "upload-artifacts"
on:
  workflow_call:

permissions:
  contents: read

jobs:
  upload_artifacts:
    name: Build and upload ${{ matrix.id }} dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: "neoforge"
            task: ":instances:neoforge:shadowJar"
          - id: "forge"
            task: ":instances:forge:shadowJar"
          - id: "bukkit"
            task: ":instances:bukkit:shadowJar"
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Read project properties
        id: properties
        uses: christian-draeger/read-properties@908f99d3334be3802ec7cb528395a69d19914e7b # 1.1.1
        with:
          path: './gradle.properties'
          properties: 'klibs.project.name'
      - name: Set up JDK
        uses: ./.github/actions/setup-jdk
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Build ${{ matrix.id }} with Gradle
        run: ./gradlew ${{ matrix.task }} --stacktrace
      - name: Upload ${{ matrix.id }} dist
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist-${{ matrix.id }}
          # ./jars is the Gradle shadowJar output directory (see instances/*/build.gradle.kts)
          path: ./jars/${{ steps.properties.outputs.klibs-project-name }}-${{ matrix.id }}*.jar
