name: "Upload Modrinth release"
on:
  workflow_call:
    secrets:
      MODRINTH_TOKEN:
        required: true
jobs:
  upload_github_release:
    name: Upload GitHub release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: "fabric"
            task: ":instances:fabric:assemble"
          - id: "forge"
            task: ":instances:forge:shadowJar"
          - id: "velocity"
            task: ":instances:velocity:shadowJar"
          - id: "bukkit"
            task: ":instances:bukkit:shadowJar"
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v5

      - uses: christian-draeger/read-properties@1.1.1
        id: properties
        with:
          path: './gradle.properties'
          properties: 'makeevrserg.project.name makeevrserg.project.version.string'

      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        name: "Download ${{ matrix.id }}"
        with:
          name: ${{ matrix.id }}
          path: ./jars/${{ matrix.id }}
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: 6NpNwzA1
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: ${{ steps.properties.outputs.makeevrserg-project-name }}-${{ matrix.id }}
          version: ${{ steps.properties.outputs.makeevrserg-project-version-string }}
          changelog: ${{ join(github.event.commits.*.message, '\n') }}
          version_type: beta
          java: |
            21
          loaders: |
            ${{ matrix.id }}
          game-versions: |
            [1.16,1.21.1)
          files: |
            ./jars/${{ matrix.id }}/*.jar
