name: "upload-modrinth-release"
on:
  workflow_call:
    secrets:
      MODRINTH_TOKEN:
        description: "Modrinth API token used to publish the release."
        required: true

permissions:
  contents: read

jobs:
  upload_modrinth_release:
    name: Upload ${{ matrix.id }} Modrinth release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [ "neoforge", "forge", "bukkit" ]
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Read project properties
        id: properties
        uses: christian-draeger/read-properties@908f99d3334be3802ec7cb528395a69d19914e7b # 1.1.1
        with:
          path: './gradle.properties'
          properties: 'klibs.project.name klibs.project.version.string'

      - name: Download ${{ matrix.id }} dist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist-${{ matrix.id }}
          path: ./dist/${{ matrix.id }}
      - name: Publish ${{ matrix.id }} to Modrinth
        uses: Kir-Antipov/mc-publish@52307b03863581dec6b652b83e597aec02ebb075 # v3.3
        with:
          modrinth-id: 6NpNwzA1
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: ${{ steps.properties.outputs.klibs-project-name }}-${{ matrix.id }}
          version: ${{ steps.properties.outputs.klibs-project-version-string }}
          changelog: ${{ join(github.event.commits.*.message, '\n') }}
          version-type: beta
          java: |
            21
          loaders: |
            ${{ matrix.id }}
          game-versions: |
            [1.16,1.21.1)
          files: |
            ./dist/${{ matrix.id }}/*.jar
