name: "Upload GitHub release"
on:
  workflow_call:
    secrets:
      ACTIONS_TOKEN:
        required: true
jobs:
  upload_github_release:
    name: Upload GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4

      - uses: christian-draeger/read-properties@1.1.1
        id: properties
        with:
          path: './gradle.properties'
          properties: 'makeevrserg.project.name makeevrserg.project.version.string'

      - uses: actions/download-artifact@7fba95161a0924506ed1ae69cdbae8371ee00b3f
        name: "Download velocity"
        with:
          name: velocity
          path: ./jars
      - uses: actions/download-artifact@7fba95161a0924506ed1ae69cdbae8371ee00b3f
        name: "Download forge"
        with:
          name: forge
          path: ./jars
      - uses: actions/download-artifact@7fba95161a0924506ed1ae69cdbae8371ee00b3f
        name: "Download fabric"
        with:
          name: fabric
          path: ./jars
      - uses: actions/download-artifact@7fba95161a0924506ed1ae69cdbae8371ee00b3f
        name: "Download bukkit"
        with:
          name: bukkit
          path: ./jars

      - name: Create release
        id: create_internal_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          files: |
            ./jars/*.jar
          tag_name: ${{ steps.properties.outputs.makeevrserg-project-version-string }}
          name: ${{ steps.properties.outputs.makeevrserg-project-name }} - ${{ steps.properties.outputs.makeevrserg-project-version-string }}
          draft: false
          prerelease: false
